version: '3.8'
services:
  db:
    image: bitnami/postgresql:16.2.0
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=cafeteria
    volumes:
      - database:/bitnami/postgresql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:8.4
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
  backend:
    image: ghcr.io/danielseregin/api:latest
    depends_on:
      - db
    restart: unless-stopped
    pull_policy: always
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/cafeteria
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    ports:
      - "9995:9995"
volumes:
  database:
